# QUIZ 1
Submitted by Russel Jade Tumanon

# Part 1

In [1]:
import numpy as np

# Creating y_hat and y arrays

Initializing y_hat with 20 linearly spaced numbers between -1 and 1.

In [2]:
y_hat = np.linspace(-1, 1, num = 20)

Initializing y with 20 linearly spaced numbers between 0 and 1.

In [3]:
y = np.linspace(0, 1, num = 20)

# Shape and Dimension

Shape of y_hat

In [4]:
y_hat.shape

(20,)

Shape of y

In [5]:
y.shape

(20,)

Dimension of y_hat

In [6]:
y_hat.ndim

1

Dimension of y

In [7]:
y.ndim

1

#  Loss Functions

# Mean Squared Error (MSE)

In [8]:
def mse(y, y_hat):
    
    #Formula for the Mean Squared Error
    #L = loss value
    L = np.square(np.subtract(y_hat, y)).mean()

    return L

mse(y, y_hat)

0.3421052631578948

# Mean Absolute Error (MAE)

In [9]:
def mae(y, y_hat):

    #Formula for Mean Absolute Error
    #L = loss value
    L = np.abs(np.subtract(y_hat, y)).mean()

    return L

mae(y, y_hat)

0.4999999999999999

# Mean Squared Logarithmic Error (MSLE)

In [10]:
def msle(y, y_hat):
    
    #If the target is never zero, we can drop the addition of 1 in the logarithm
    #L = loss value
    if all(i > 0 for i in y_hat) and all(j > 0 for j in y):
        L = np.square(np.subtract(np.log(y_hat), np.log(y))).mean()
        return L
    
    #Target variable should be non-negative but can also be equal to zero
    elif all(i >= 0 for i in y_hat) and all(j >= 0 for j in y):
        L = np.square(np.subtract(np.log(y_hat + 1 ), np.log(y + 1))).mean()
        return L
    else:
        print("Negative values detected! We cannot use MSLE when targets contain negative values.")

msle(y, y_hat)

Negative values detected! We cannot use MSLE when targets contain negative values.


# Mean Absolute Percentage Error (MAPE)

In [11]:
def mae(y, y_hat):
    
    #Checks if the denominator is 0
    #L = loss value
    if y.all() == 0:
        print("Infinity%. The denominator is 0.")

    else:
        L = (np.abs((y_hat-y)/y)).mean()*100
        return L

mae(y, y_hat)

Infinity%. The denominator is 0.


# Part 2

# Arange and Reshape

# Arange function

Creating 1d array M using the arange function.

In [12]:
M = np.arange(1,17)

# Reshaping Array

Reshaping M into 4x4 array and storing it to N.

In [13]:
N = M.reshape(4,4)

# Row and Column

Getting the 2nd row of N.

In [14]:
N[1]

array([5, 6, 7, 8])

Getting the minimum values for each column of N.

In [15]:
np.min(N, axis = 0)

array([1, 2, 3, 4])

Getting the locations (index) of the minimum values for each column of N.

In [16]:
N_min = np.where(np.min(N, axis = 0))

#printing each index respectively separated by space
for i in N_min:
    print(i)

[0 1 2 3]


# Vector and Matrix

Getting the average of the whole matrix.

In [17]:
np.mean(N)

8.5

Creating a vector V with 4 elements, all 1.

In [18]:
lst = [1,1,1,1]
V = np.array(lst)

 Dot product of N and V

In [19]:
np.dot(N, V)

array([10, 26, 42, 58])

# ---END OF QUIZ 1---